os: Visual Studio 2015

# Clone directly into GOPATH.
<<<<<<< HEAD
clone_folder: c:\gopath\src\github.com\ethereum\go-ethereum
=======
clone_folder: C:\gopath\src\github.com\ethereum\go-ethereum
>>>>>>> 1d06e41f04d75c31334c455063e9ec7b4136bf23
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
<<<<<<< HEAD
    # Go stuff
    GOPATH: c:\gopath
    GO: c:\go\bin\go
    GOROOT: c:\go
    CC: C:\msys64\mingw64\bin\gcc.exe
    # MSYS2 stuff
    MSYS2_ARCH: x86_64
    MSYSTEM: MINGW64
    PATH: C:\msys64\mingw64\bin\;%PATH%

install:
  - "%GO% version"
  - "%CC% --version"

build_script:
  - "%GO% run build\\ci.go install"

test_script:
  - "%GO% run build\\ci.go test -vet -coverage"

after_build:
  - "%GO% run build\\ci.go archive -type zip"

artifacts:
  - path: geth-*.zip
=======
    GOPATH: C:\gopath
    CC: gcc.exe
  matrix:
    - GETH_ARCH: amd64
      MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
    - GETH_ARCH: 386
      MSYS2_ARCH: i686
      MSYS2_BITS: 32
      MSYSTEM: MINGW32
      PATH: C:\msys64\mingw32\bin\;C:\Program Files (x86)\NSIS\;%PATH%

install:
  - git submodule update --init
  - rmdir C:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.9.windows-%GETH_ARCH%.zip
  - 7z x go1.9.windows-%GETH_ARCH%.zip -y -oC:\ > NUL
  - go version
  - gcc --version

build_script:
  - go run build\ci.go install

after_build:
  - go run build\ci.go archive -type zip -signer WINDOWS_SIGNING_KEY -upload gethstore/builds
  - go run build\ci.go nsis -signer WINDOWS_SIGNING_KEY -upload gethstore/builds

test_script:
  - set CGO_ENABLED=1
  - go run build\ci.go test -coverage
>>>>>>> 1d06e41f04d75c31334c455063e9ec7b4136bf23
